---
Name: innoweb-robots-multisites
Only:
  classexists: 'Symbiote\Multisites\Multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\Robots\Extensions\ConfigExtension

---
Name: innoweb-robots-nomultisites
Except:
  classexists: 'Symbiote\Multisites\Multisites'
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\Robots\Extensions\ConfigExtension
