---
Name: innoweb-robots-routes-multisites
After:
  - '*'
  - 'multisitesmodelascontrollerroutes'
  - 'modelascontrollercatchallroute'
Only:
  moduleexists: 'symbiote/silverstripe-multisites'
---
SilverStripe\Control\Director:
  rules:
    '': Symbiote\Multisites\Control\MultisitesRootController
    'robots.txt': Innoweb\Robots\Controllers\RobotsController
    '$URLSegment//$Action/$ID/$OtherID': Symbiote\Multisites\Control\MultisitesFrontController

---
Name: innoweb-robots-routes-no-multisites
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
---
SilverStripe\Control\Director:
  rules:
    'robots.txt': Innoweb\Robots\Controllers\RobotsController
